name: Deploy to GitHub Pages

# Gatilhos: Quando o robô deve trabalhar
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

# Permissões: O "crachá" de acesso do robô
permissions:
  contents: read
  pages: write
  id-token: write

# Concorrência: Organiza a fila de deploys
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # O Servidor (Runner): Onde a mágica acontece
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixa o seu código para o servidor
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Passo 2: Verifica se a pasta src existe
      - name: Verificar pasta src
        run: |
          if [ ! -d "src" ]; then
            echo "Pasta 'src' não encontrada""
            exit 1
          fi
          echo "Pasta 'src' encontrada!"

      # Passo 3: Verifica se o CSS existe no novo caminho
      - name: Verificar arquivo CSS
        run: |
          if [ ! -f "src/css/style.css" ]; then
            echo "Arquivo src/css/style.css não encontrado!"
            exit 1
          fi
          echo "Arquivo CSS encontrado!"

      # Passo 4: valida sintaxe HTML
      - name: Validar sintaxe HTML
        uses: htmlhint/htmlhint-action@v2
        with:
          target_pattern: "src/index.html"

      # Passo 5: Configura o ambiente para o GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Passo 6: Checar arquivos estáticos
      - name: Checar arquivos estáticos
        run: |
          ls -R
          echo "Todos os arquivos foram carregados no runner"

      # Passo 7: Empacota o site (HTML/CSS) para o servidor
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "src" # Define que o site está na raiz do projeto

      # Passo 5: Publica o site oficialmente
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
